# Generated by Django 3.1 on 2020-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
